language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
env:
  - 'TEST_DIR=packages/eslint-config-airbnb'
  - 'TEST_DIR=packages/eslint-config-airbnb-base'
before_install:
  - 'if [ -n "${TEST_DIR-}" ]; then cd "${TEST_DIR}" ; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" != "0.9" ]; then case "$(npm --version)" in 1.*) npm install -g npm@1.4.28 ;; 2.*) npm install -g npm@2 ;; esac ; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" != "0.6" ] && [ "${TRAVIS_NODE_VERSION}" != "0.9" ]; then npm install -g npm; fi'
script:
  - 'if [ -n "${TEST_DIR-}" ]; then npm run travis ; fi'
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
sudo: false
matrix:
  include:
    - node_js: "node"
      env: LINT=true
  fast_finish: true
